name: '${name}'
author: Lysandre B.
version: '${version}'
main: fr.hashtek.tekore.bukkit.Tekore
api-version: '1.16'
commands:
  whoami:
    description: "man whoami"
    usage: "/whoami"
  friend:
    aliases: [f]
    description: "Système d'amis"
    usage: "/friend [list [<page>]] [gui] [add <name>] [remove/rm <name>]"
