name: '${name}'
author: Lysandre B.
version: '${version}'
main: fr.hashtek.tekore.spigot.Tekore
api-version: '1.16'
commands:
  whoami:
    description: "man whoami"
    usage: "/whoami"
  friend:
    aliases: [f]
    description: "Système d'amis"
    usage: "/friend [list [<page>]] [add <name>] [remove/rm <name>]"
  party:
    aliases: [p]
    description: "Système de party"
    usage: "/party [status] [create] [disband] [add <name>] [remove/rm <name>] [kick <name>] [leave] [promote <name>] [accept <name>] [deny <name>]"
  accountdump:
  accountedit:
  rankpush:
