name: '${name}'
author: Lysandre B.
version: '${version}'
main: fr.hashtek.tekore.bukkit.Tekore
commands:
  whoami:
    description: "man whoami"
    usage: "/whoami"
  logs:
    description: ""
    usage: "/logs [<category>] [<find>]"